sudo: false
language: python
python:
  - "3.6"
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip setuptools
  - pip install -r dev-requirements.txt -U
  - pip freeze
script: py.test --cov=./
after_success:
  - codecov
